upload config file with yaml, not viper
OpsLevel/kubectl-opslevel pull request #222
Opened 2023-12-20 21:56 UTC by davidbloss

## Issues

## Changelog

Update `kubectl config` to load its config with `yaml. Unmarshal()` rather than `viper.Unmarshal()`

- [X] List your changes here
- [X] Make a `changie` entry

## Tophatting

2023-12-20 22:15 UTC, taimoor-at-opslevel requested changes

2023-12-20 22:15 UTC, taimoor-at-opslevel commented on src/cmd/root.go
> -func readConfig() {
I think this function and the call to it on line 63 should be retained to a degree. We still need to do the operations on line 89, 90 afaict.

2023-12-20 22:15 UTC, taimoor-at-opslevel commented on src/cmd/config.go
> -	v := &common.ConfigVersion{}
The `type ConfigVersion struct` in config.go should also be deleted since it's unused now.

2023-12-20 22:15 UTC, taimoor-at-opslevel commented on src/cmd/root.go
> -		if cfgFile == "." {
Also, IIRC you can never parse `.` as an argument in the CLI, so this should have actually been `-`.

2023-12-20 22:15 UTC, taimoor-at-opslevel commented on src/cmd/config.go
> +	yamlData, err := os.ReadFile(cfgFile)
Need to port over the logic from root.go `readConfig()` to:

1. If `cfgFile == "-"` read the config from stdin as yaml
2. If the file at location `cfgFile` is found, read it. This is how the code works now.
3. If the file at location `cfgFile` is not found, read the file `$HOME/opslevel.yaml`

2024-01-05 17:09 UTC, taimoorgit commented
See https://github.com/OpsLevel/kubectl-opslevel/pull/222

2024-01-05 17:09 UTC, closed without merging